import { selectVehicleDetails, selectVehicles } from 'src/app/store/vehicles/vehicles.selectors';
import { Dictionary } from '@ngrx/entity';
import { Vehicle, VehicleDetails } from 'src/app/shared/interfaces';

const mockedVehicleDetails1 = {
    marka: 'marka 1',
    model: 'model 1',
    'rodzaj-pojazdu': 'value',
    'kategoria-pojazdu': 'value',
    typ: 'value',
    wariant: 'value',
    'pochodzenie-pojazdu': 'value',
    'rok-produkcji': 'value',
    'data-pierwszej-rejestracji-w-kraju': 'value',
    'pojemnosc-skokowa-silnika': 1,
    'masa-wlasna': 1000,
    'rodzaj-paliwa': 'value',
    'wojewodztwo-kod': 'value',
    wersja: 'value',
    'podrodzaj-pojazdu': 'value',
    'przeznaczenie-pojazdu': 'value',
    'rodzaj-tabliczki-znamionowej': 'value',
    'sposob-produkcji': 'value',
    'data-ostatniej-rejestracji-w-kraju': 'value',
    'data-rejestracji-za-granica': 'value',
    'stosunek-mocy-silnika-do-masy-wlasnej-motocykle': 1,
    'moc-netto-silnika': 1,
    'moc-netto-silnika-hybrydowego': 1,
    'masa-pojazdu-gotowego-do-jazdy': 1,
    'dopuszczalna-masa-calkowita': 1,
    'max-masa-calkowita': 1,
    'dopuszczalna-ladownosc': 1,
    'max-ladownosc': 1,
    'dopuszczalna-masa-calkowita-zespolu-pojazdow': 1,
    'liczba-osi': 1,
    'dopuszczalny-nacisk-osi': 1,
    'maksymalny-nacisk-osi': 1,
    'max-masa-calkowita-przyczepy-z-hamulcem': 1,
    'max-masa-calkowita-przyczepy-bez-hamulca': 1,
    'liczba-miejsc-ogolem': 1,
    'liczba-miejsc-siedzacych': 1,
    'liczba-miejsc-stojacych': 1,
    'rodzaj-pierwszego-paliwa-alternatywnego': 'value',
    'rodzaj-drugiego-paliwa-alternatywnego': 'value',
    'srednie-zuzycie-paliwa': 1,
    'poziom-emisji-co2': 1,
    'rodzaj-zawieszenia': 'value',
    'wyposazenie-i-rodzaj-urzadzenia-radarowego': 'value',
    hak: true,
    'kierownica-po-prawej-stronie': true,
    'kierownica-po-prawej-stronie-pierwotnie': true,
    'katalizator-pochlaniacz': true,
    'nazwa-producenta': 'value',
    'kod-instytutu-transaportu-samochodowego': 'value',
    'rozstaw-kol-osi-kierowanej-pozostalych-osi': 'value',
    'max-rozstaw-kol': 1,
    'avg-rozstaw-kol': 1,
    'min-rozstaw-kol': 1,
    'redukcja-emisji-spalin': 1,
    'data-pierwszej-rejestracji': 'value',
    'rodzaj-kodowania-rodzaj-podrodzaj-przeznaczenie': 'value',
    'kod-rodzaj-podrodzaj-przeznaczenie': 'value',
    'data-wyrejestrowania-pojazdu': 'value',
    'przyczyna-wyrejestrowania-pojazdu': 'value',
    'data-wprowadzenia-danych': 'value',
    'rejestracja-wojewodztwo': 'value',
    'rejestracja-powiat': 'value',
    'rejestracja-gmina': 'value',
    'wlasciciel-wojewodztwo': 'value',
    'wlasciciel-powiat': 'value',
    'wlasciciel-gmina': 'value',
    'wlasciciel-wojewodztwo-kod': 'value',
    'poziom-emisji-co2-paliwo-alternatywne-1': 1,
};

const mockedVehicleDetails2 = {
    marka: 'marka 2',
    model: 'model 2',
    'rodzaj-pojazdu': 'value',
    'kategoria-pojazdu': 'value',
    typ: 'value',
    wariant: 'value',
    'pochodzenie-pojazdu': 'value',
    'rok-produkcji': 'value',
    'data-pierwszej-rejestracji-w-kraju': 'value',
    'pojemnosc-skokowa-silnika': 1,
    'masa-wlasna': 1000,
    'rodzaj-paliwa': 'value',
    'wojewodztwo-kod': 'value',
    wersja: 'value',
    'podrodzaj-pojazdu': 'value',
    'przeznaczenie-pojazdu': 'value',
    'rodzaj-tabliczki-znamionowej': 'value',
    'sposob-produkcji': 'value',
    'data-ostatniej-rejestracji-w-kraju': 'value',
    'data-rejestracji-za-granica': 'value',
    'stosunek-mocy-silnika-do-masy-wlasnej-motocykle': 1,
    'moc-netto-silnika': 1,
    'moc-netto-silnika-hybrydowego': 1,
    'masa-pojazdu-gotowego-do-jazdy': 1,
    'dopuszczalna-masa-calkowita': 1,
    'max-masa-calkowita': 1,
    'dopuszczalna-ladownosc': 1,
    'max-ladownosc': 1,
    'dopuszczalna-masa-calkowita-zespolu-pojazdow': 1,
    'liczba-osi': 1,
    'dopuszczalny-nacisk-osi': 1,
    'maksymalny-nacisk-osi': 1,
    'max-masa-calkowita-przyczepy-z-hamulcem': 1,
    'max-masa-calkowita-przyczepy-bez-hamulca': 1,
    'liczba-miejsc-ogolem': 1,
    'liczba-miejsc-siedzacych': 1,
    'liczba-miejsc-stojacych': 1,
    'rodzaj-pierwszego-paliwa-alternatywnego': 'value',
    'rodzaj-drugiego-paliwa-alternatywnego': 'value',
    'srednie-zuzycie-paliwa': 1,
    'poziom-emisji-co2': 1,
    'rodzaj-zawieszenia': 'value',
    'wyposazenie-i-rodzaj-urzadzenia-radarowego': 'value',
    hak: true,
    'kierownica-po-prawej-stronie': true,
    'kierownica-po-prawej-stronie-pierwotnie': true,
    'katalizator-pochlaniacz': true,
    'nazwa-producenta': 'value',
    'kod-instytutu-transaportu-samochodowego': 'value',
    'rozstaw-kol-osi-kierowanej-pozostalych-osi': 'value',
    'max-rozstaw-kol': 1,
    'avg-rozstaw-kol': 1,
    'min-rozstaw-kol': 1,
    'redukcja-emisji-spalin': 1,
    'data-pierwszej-rejestracji': 'value',
    'rodzaj-kodowania-rodzaj-podrodzaj-przeznaczenie': 'value',
    'kod-rodzaj-podrodzaj-przeznaczenie': 'value',
    'data-wyrejestrowania-pojazdu': 'value',
    'przyczyna-wyrejestrowania-pojazdu': 'value',
    'data-wprowadzenia-danych': 'value',
    'rejestracja-wojewodztwo': 'value',
    'rejestracja-powiat': 'value',
    'rejestracja-gmina': 'value',
    'wlasciciel-wojewodztwo': 'value',
    'wlasciciel-powiat': 'value',
    'wlasciciel-gmina': 'value',
    'wlasciciel-wojewodztwo-kod': 'value',
    'poziom-emisji-co2-paliwo-alternatywne-1': 1,
};

const mockedVehicleDetails3 = {
    marka: 'marka 3',
    model: 'model 3',
    'rodzaj-pojazdu': 'value',
    'kategoria-pojazdu': 'value',
    typ: 'value',
    wariant: 'value',
    'pochodzenie-pojazdu': 'value',
    'rok-produkcji': 'value',
    'data-pierwszej-rejestracji-w-kraju': 'value',
    'pojemnosc-skokowa-silnika': 1,
    'masa-wlasna': 1000,
    'rodzaj-paliwa': 'value',
    'wojewodztwo-kod': 'value',
    wersja: 'value',
    'podrodzaj-pojazdu': 'value',
    'przeznaczenie-pojazdu': 'value',
    'rodzaj-tabliczki-znamionowej': 'value',
    'sposob-produkcji': 'value',
    'data-ostatniej-rejestracji-w-kraju': 'value',
    'data-rejestracji-za-granica': 'value',
    'stosunek-mocy-silnika-do-masy-wlasnej-motocykle': 1,
    'moc-netto-silnika': 1,
    'moc-netto-silnika-hybrydowego': 1,
    'masa-pojazdu-gotowego-do-jazdy': 1,
    'dopuszczalna-masa-calkowita': 1,
    'max-masa-calkowita': 1,
    'dopuszczalna-ladownosc': 1,
    'max-ladownosc': 1,
    'dopuszczalna-masa-calkowita-zespolu-pojazdow': 1,
    'liczba-osi': 1,
    'dopuszczalny-nacisk-osi': 1,
    'maksymalny-nacisk-osi': 1,
    'max-masa-calkowita-przyczepy-z-hamulcem': 1,
    'max-masa-calkowita-przyczepy-bez-hamulca': 1,
    'liczba-miejsc-ogolem': 1,
    'liczba-miejsc-siedzacych': 1,
    'liczba-miejsc-stojacych': 1,
    'rodzaj-pierwszego-paliwa-alternatywnego': 'value',
    'rodzaj-drugiego-paliwa-alternatywnego': 'value',
    'srednie-zuzycie-paliwa': 1,
    'poziom-emisji-co2': 1,
    'rodzaj-zawieszenia': 'value',
    'wyposazenie-i-rodzaj-urzadzenia-radarowego': 'value',
    hak: true,
    'kierownica-po-prawej-stronie': true,
    'kierownica-po-prawej-stronie-pierwotnie': true,
    'katalizator-pochlaniacz': true,
    'nazwa-producenta': 'value',
    'kod-instytutu-transaportu-samochodowego': 'value',
    'rozstaw-kol-osi-kierowanej-pozostalych-osi': 'value',
    'max-rozstaw-kol': 1,
    'avg-rozstaw-kol': 1,
    'min-rozstaw-kol': 1,
    'redukcja-emisji-spalin': 1,
    'data-pierwszej-rejestracji': 'value',
    'rodzaj-kodowania-rodzaj-podrodzaj-przeznaczenie': 'value',
    'kod-rodzaj-podrodzaj-przeznaczenie': 'value',
    'data-wyrejestrowania-pojazdu': 'value',
    'przyczyna-wyrejestrowania-pojazdu': 'value',
    'data-wprowadzenia-danych': 'value',
    'rejestracja-wojewodztwo': 'value',
    'rejestracja-powiat': 'value',
    'rejestracja-gmina': 'value',
    'wlasciciel-wojewodztwo': 'value',
    'wlasciciel-powiat': 'value',
    'wlasciciel-gmina': 'value',
    'wlasciciel-wojewodztwo-kod': 'value',
    'poziom-emisji-co2-paliwo-alternatywne-1': 1,
};

describe('vehicles selectors', () => {

    const mockedVehiclesState: Dictionary<Vehicle | { attributes: Partial<VehicleDetails> }> = {
        'sample-id-1': {
            id: 'sample-id-1',
            type: 'sample type',
            attributes: mockedVehicleDetails1,
            links: null,
        },
        'sample-id-2': {
            id: 'sample-id-2',
            type: 'sample type',
            attributes: mockedVehicleDetails2,
            links: null,
        },
        'sample-id-3': {
            id: 'sample-id-3',
            type: 'sample type',
            attributes: mockedVehicleDetails3,
            links: null,
        },
    };

    describe('selectVehicle', () => {
        it('should return vehicle details by given id', () => {
            expect(selectVehicleDetails.projector(mockedVehiclesState, { id: 'sample-id-1' })).toEqual(mockedVehicleDetails1);
        });
    });

    describe('selectVehicles', () => {
        it('should return vehicles array by given ids', () => {
            expect(selectVehicles.projector(mockedVehiclesState, { ids: [ 'sample-id-1', 'sample-id-2' ] })).toEqual([
                {
                    id: 'sample-id-1',
                    type: 'sample type',
                    attributes: mockedVehicleDetails1,
                    links: null,
                },
                {
                    id: 'sample-id-2',
                    type: 'sample type',
                    attributes: mockedVehicleDetails2,
                    links: null,
                },
            ]);
        });
    });
});
